// <auto-generated />
using Carpark.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Carpark.Database.Migrations
{
    [DbContext(typeof(CarparkContext))]
    [Migration("20230827233458_seedWithRandomData")]
    partial class seedWithRandomData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Carpark.Database.Entities.Car", b =>
                {
                    b.Property<string>("LicensePlate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConstructionYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("LicensePlate");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            LicensePlate = "LL575V",
                            Colour = "Beige",
                            Comments = "RAM",
                            ConstructionYear = 2016,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "VK489V",
                            Colour = "Blue",
                            Comments = "hardware Junction",
                            ConstructionYear = 2020,
                            Status = 5
                        },
                        new
                        {
                            LicensePlate = "BV145P",
                            Colour = "Black",
                            Comments = "scale exuding Frozen",
                            ConstructionYear = 2018,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "PT286N",
                            Colour = "Pink",
                            Comments = "plum",
                            ConstructionYear = 2013,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "DB113G",
                            Colour = "Pink",
                            Comments = "card Books Libyan Dinar",
                            ConstructionYear = 2014,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "GN658W",
                            Colour = "White",
                            Comments = "Wisconsin Concrete Berkshire",
                            ConstructionYear = 2014,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "NL262L",
                            Colour = "Blue",
                            Comments = "matrix Facilitator bleeding-edge",
                            ConstructionYear = 2020,
                            Status = 5
                        },
                        new
                        {
                            LicensePlate = "DP065B",
                            Colour = "Red",
                            Comments = "index",
                            ConstructionYear = 2015,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "GG052Y",
                            Colour = "Orange",
                            Comments = "radical",
                            ConstructionYear = 2023,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "LZ590R",
                            Colour = "Black",
                            Comments = "HDD",
                            ConstructionYear = 2020,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "GX841D",
                            Colour = "Blue",
                            Comments = "Stream hacking back up",
                            ConstructionYear = 2015,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "JM702J",
                            Colour = "Red",
                            Comments = "Unbranded Fresh Car",
                            ConstructionYear = 2019,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "BD243K",
                            Colour = "Black",
                            Comments = "Associate Metal",
                            ConstructionYear = 2013,
                            Status = 5
                        },
                        new
                        {
                            LicensePlate = "PT198F",
                            Colour = "Yellow",
                            Comments = "plug-and-play Lari Interactions",
                            ConstructionYear = 2023,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "YF356K",
                            Colour = "Orange",
                            Comments = "Integration deposit",
                            ConstructionYear = 2017,
                            Status = 5
                        },
                        new
                        {
                            LicensePlate = "BG140V",
                            Colour = "Blue",
                            Comments = "deposit system Practical",
                            ConstructionYear = 2015,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "SW187X",
                            Colour = "Purple",
                            Comments = "ivory",
                            ConstructionYear = 2019,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "FM213J",
                            Colour = "Beige",
                            Comments = "Distributed",
                            ConstructionYear = 2014,
                            Status = 5
                        },
                        new
                        {
                            LicensePlate = "WS078S",
                            Colour = "Purple",
                            Comments = "bandwidth Refined",
                            ConstructionYear = 2014,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "LG554X",
                            Colour = "White",
                            Comments = "Borders Kip",
                            ConstructionYear = 2016,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "RZ645Y",
                            Colour = "Blue",
                            Comments = "interface Bosnia and Herzegovina Buckinghamshire",
                            ConstructionYear = 2013,
                            Status = 5
                        },
                        new
                        {
                            LicensePlate = "TD048S",
                            Colour = "White",
                            Comments = "payment Maryland",
                            ConstructionYear = 2015,
                            Status = 5
                        },
                        new
                        {
                            LicensePlate = "HL914K",
                            Colour = "Purple",
                            Comments = "copying",
                            ConstructionYear = 2016,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "KP803M",
                            Colour = "Beige",
                            Comments = "eyeballs Vista",
                            ConstructionYear = 2017,
                            Status = 5
                        },
                        new
                        {
                            LicensePlate = "KM612N",
                            Colour = "Orange",
                            Comments = "Inlet Savings Account",
                            ConstructionYear = 2017,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "DL596P",
                            Colour = "Green",
                            Comments = "Intelligent Metal Keyboard metrics Mobility",
                            ConstructionYear = 2013,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "RN925K",
                            Colour = "Beige",
                            Comments = "connecting Wyoming wireless",
                            ConstructionYear = 2016,
                            Status = 5
                        },
                        new
                        {
                            LicensePlate = "KP845B",
                            Colour = "Purple",
                            Comments = "Wooden cross-platform Facilitator",
                            ConstructionYear = 2016,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "LT711W",
                            Colour = "Beige",
                            Comments = "withdrawal",
                            ConstructionYear = 2014,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "GX103Z",
                            Colour = "Beige",
                            Comments = "salmon quantifying",
                            ConstructionYear = 2022,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "FS275P",
                            Colour = "Brown",
                            Comments = "Public-key Missouri feed",
                            ConstructionYear = 2023,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "LH331H",
                            Colour = "Pink",
                            Comments = "Brunei Darussalam programming Bedfordshire",
                            ConstructionYear = 2013,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "JM619K",
                            Colour = "Pink",
                            Comments = "card",
                            ConstructionYear = 2014,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "WT431K",
                            Colour = "Black",
                            Comments = "Virginia RAM",
                            ConstructionYear = 2023,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "BV071H",
                            Colour = "Yellow",
                            Comments = "haptic",
                            ConstructionYear = 2013,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "TD428Y",
                            Colour = "Orange",
                            Comments = "e-business",
                            ConstructionYear = 2017,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "ZN749V",
                            Colour = "Beige",
                            Comments = "24/7 Metal Industrial & Shoes",
                            ConstructionYear = 2021,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "JK566B",
                            Colour = "White",
                            Comments = "vortals backing up",
                            ConstructionYear = 2023,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "LX864X",
                            Colour = "Blue",
                            Comments = "Team-oriented",
                            ConstructionYear = 2020,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "VM128Z",
                            Colour = "Orange",
                            Comments = "withdrawal calculating Program",
                            ConstructionYear = 2019,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "DH389H",
                            Colour = "White",
                            Comments = "Ergonomic payment",
                            ConstructionYear = 2015,
                            Status = 5
                        },
                        new
                        {
                            LicensePlate = "GM372F",
                            Colour = "Beige",
                            Comments = "Specialist groupware",
                            ConstructionYear = 2017,
                            Status = 5
                        },
                        new
                        {
                            LicensePlate = "GM869B",
                            Colour = "White",
                            Comments = "Global transmitting",
                            ConstructionYear = 2023,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "LN838D",
                            Colour = "Beige",
                            Comments = "Stravenue",
                            ConstructionYear = 2015,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "GS598T",
                            Colour = "Brown",
                            Comments = "Maryland Generic Wooden Bike",
                            ConstructionYear = 2015,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "VZ872Z",
                            Colour = "Blue",
                            Comments = "communities Alley",
                            ConstructionYear = 2015,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "LT218Y",
                            Colour = "Yellow",
                            Comments = "New York",
                            ConstructionYear = 2021,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "WZ952J",
                            Colour = "Brown",
                            Comments = "next generation",
                            ConstructionYear = 2019,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "NH523H",
                            Colour = "Green",
                            Comments = "Games, Books & Shoes",
                            ConstructionYear = 2021,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "GV946G",
                            Colour = "Purple",
                            Comments = "Fantastic Wooden Ball",
                            ConstructionYear = 2014,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "ZP345R",
                            Colour = "White",
                            Comments = "ubiquitous backing up",
                            ConstructionYear = 2016,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "VZ031P",
                            Colour = "Pink",
                            Comments = "Home Loan Account backing up",
                            ConstructionYear = 2022,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "NZ381M",
                            Colour = "Purple",
                            Comments = "Investment Account Fresh",
                            ConstructionYear = 2018,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "RP173S",
                            Colour = "Yellow",
                            Comments = "Organized Bolivia Handmade",
                            ConstructionYear = 2013,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "XB758G",
                            Colour = "Black",
                            Comments = "end-to-end open-source",
                            ConstructionYear = 2018,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "TV482Y",
                            Colour = "Orange",
                            Comments = "Investment Account",
                            ConstructionYear = 2022,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "VS569P",
                            Colour = "Yellow",
                            Comments = "Tugrik Practical",
                            ConstructionYear = 2023,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "MR903G",
                            Colour = "Pink",
                            Comments = "Generic Fresh Keyboard Versatile",
                            ConstructionYear = 2018,
                            Status = 5
                        },
                        new
                        {
                            LicensePlate = "XP934M",
                            Colour = "Brown",
                            Comments = "AI Rustic Unbranded Soft Bacon",
                            ConstructionYear = 2014,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "NY818N",
                            Colour = "Purple",
                            Comments = "Harbors",
                            ConstructionYear = 2015,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "TH667F",
                            Colour = "White",
                            Comments = "invoice Orchard forecast",
                            ConstructionYear = 2020,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "LW428B",
                            Colour = "Purple",
                            Comments = "Lebanese Pound Belize Dollar transmit",
                            ConstructionYear = 2016,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "SF067N",
                            Colour = "Yellow",
                            Comments = "haptic",
                            ConstructionYear = 2023,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "HB531K",
                            Colour = "Beige",
                            Comments = "Norway",
                            ConstructionYear = 2022,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "RK594F",
                            Colour = "Blue",
                            Comments = "Multi-layered Buckinghamshire Personal Loan Account",
                            ConstructionYear = 2022,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "LM972F",
                            Colour = "Black",
                            Comments = "framework success",
                            ConstructionYear = 2013,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "FN640L",
                            Colour = "Brown",
                            Comments = "Unbranded",
                            ConstructionYear = 2018,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "JL708N",
                            Colour = "Purple",
                            Comments = "indigo",
                            ConstructionYear = 2023,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "MM247B",
                            Colour = "Beige",
                            Comments = "Surinam Dollar",
                            ConstructionYear = 2020,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "XD629Y",
                            Colour = "Brown",
                            Comments = "wireless",
                            ConstructionYear = 2021,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "JF576K",
                            Colour = "Yellow",
                            Comments = "Infrastructure Sleek Soft Hat magnetic",
                            ConstructionYear = 2023,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "KZ702V",
                            Colour = "Beige",
                            Comments = "Graphic Interface Rustic Metal Hat",
                            ConstructionYear = 2018,
                            Status = 5
                        },
                        new
                        {
                            LicensePlate = "GR409H",
                            Colour = "Brown",
                            Comments = "Wooden",
                            ConstructionYear = 2021,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "DL134G",
                            Colour = "Brown",
                            Comments = "Data",
                            ConstructionYear = 2022,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "ZG386X",
                            Colour = "Purple",
                            Comments = "strategic Gorgeous",
                            ConstructionYear = 2021,
                            Status = 5
                        },
                        new
                        {
                            LicensePlate = "MF095F",
                            Colour = "Purple",
                            Comments = "iterate Metrics",
                            ConstructionYear = 2021,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "HW596S",
                            Colour = "Blue",
                            Comments = "Rubber",
                            ConstructionYear = 2022,
                            Status = 5
                        },
                        new
                        {
                            LicensePlate = "LK140B",
                            Colour = "Green",
                            Comments = "bypass Pa'anga Concrete",
                            ConstructionYear = 2015,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "TW479S",
                            Colour = "Orange",
                            Comments = "India plum",
                            ConstructionYear = 2013,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "JB897K",
                            Colour = "Orange",
                            Comments = "Shoals Multi-layered",
                            ConstructionYear = 2013,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "DM285X",
                            Colour = "Black",
                            Comments = "Surinam Dollar hack",
                            ConstructionYear = 2013,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "KR599F",
                            Colour = "Orange",
                            Comments = "Licensed Metal Chicken attitude Intelligent Cotton Car",
                            ConstructionYear = 2021,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "BR268K",
                            Colour = "Orange",
                            Comments = "zero tolerance Massachusetts",
                            ConstructionYear = 2016,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "SX867D",
                            Colour = "Blue",
                            Comments = "input Fantastic Metal Shoes",
                            ConstructionYear = 2016,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "HN370T",
                            Colour = "Yellow",
                            Comments = "deposit cutting-edge",
                            ConstructionYear = 2022,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "MD220M",
                            Colour = "Red",
                            Comments = "Handcrafted Cotton Chicken RAM",
                            ConstructionYear = 2018,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "GD591V",
                            Colour = "Purple",
                            Comments = "Wells Savings Account Terrace",
                            ConstructionYear = 2022,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "ZK074X",
                            Colour = "Yellow",
                            Comments = "Tasty withdrawal object-oriented",
                            ConstructionYear = 2016,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "ZY455L",
                            Colour = "Purple",
                            Comments = "Program Engineer",
                            ConstructionYear = 2020,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "XJ817D",
                            Colour = "Purple",
                            Comments = "Gibraltar Pound",
                            ConstructionYear = 2015,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "VL671Y",
                            Colour = "Purple",
                            Comments = "Silver mission-critical withdrawal",
                            ConstructionYear = 2020,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "KD932Y",
                            Colour = "Beige",
                            Comments = "Djibouti Franc Licensed Plastic Keyboard",
                            ConstructionYear = 2021,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "XJ620S",
                            Colour = "Red",
                            Comments = "Digitized",
                            ConstructionYear = 2013,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "RB913K",
                            Colour = "Beige",
                            Comments = "Beauty, Outdoors & Baby program",
                            ConstructionYear = 2018,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "NS235B",
                            Colour = "Brown",
                            Comments = "invoice JBOD",
                            ConstructionYear = 2023,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "ZT610P",
                            Colour = "White",
                            Comments = "input Bedfordshire 1080p",
                            ConstructionYear = 2021,
                            Status = 4
                        },
                        new
                        {
                            LicensePlate = "DB488S",
                            Colour = "Brown",
                            Comments = "Liaison Electronics, Kids & Health synergies",
                            ConstructionYear = 2021,
                            Status = 1
                        },
                        new
                        {
                            LicensePlate = "FW651S",
                            Colour = "Purple",
                            Comments = "generate deposit",
                            ConstructionYear = 2023,
                            Status = 2
                        },
                        new
                        {
                            LicensePlate = "SH640F",
                            Colour = "Green",
                            Comments = "Awesome Granite Bacon",
                            ConstructionYear = 2021,
                            Status = 5
                        },
                        new
                        {
                            LicensePlate = "TT120J",
                            Colour = "Purple",
                            Comments = "capability lime",
                            ConstructionYear = 2023,
                            Status = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
